name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
            - نام: راه‌اندازی .NET Core SDK
  موارد استفاده: actions/setup-dotnet@v3.4.2
  با:
    # نسخه(های) SDK اختیاری برای استفاده. در صورت عدم ارائه، نسخه global.json در صورت موجود بودن نصب خواهد شد. مثال‌ها: 2.2.104، 3.1، 3.1.x، 3.x، 6.0.2xx
    نسخه دات نت: # اختیاری
    # کیفیت ساخت اختیاری. مقادیر ممکن عبارتند از: روزانه، امضا شده، معتبر، پیش‌نمایش، ga.
    کیفیت دات‌نت: # اختیاری
    # مکان اختیاری global.json، اگر global.json شما در ریشه مخزن قرار ندارد.
    فایل-json-جهانی: # اختیاری
    # منبع بسته اختیاری برای تنظیم احراز هویت. هرگونه NuGet.config موجود در ریشه مخزن را بررسی کرده و یک NuGet.config موقت با استفاده از متغیر محیطی NUGET_AUTH_TOKEN به عنوان ClearTextPassword ارائه می‌دهد.
    آدرس منبع: # اختیاری
    # مالک اختیاری برای استفاده از بسته‌های سازمان‌ها/کاربران رجیستری بسته گیت‌هاب غیر از مالک مخزن فعلی. فقط در صورتی استفاده می‌شود که URL GPR نیز در source-url ارائه شده باشد.
    مالک: # اختیاری
    # مکان NuGet.config اختیاری است، اگر NuGet.config شما در ریشه مخزن قرار ندارد.
    فایل پیکربندی: # اختیاری
    # ورودی اختیاری برای فعال کردن ذخیره سازی پوشه بسته های سراسری NuGet
    حافظه پنهان: # اختیاری
    # برای مشخص کردن مسیر فایل وابستگی استفاده می‌شود: packages.lock.json. از کاراکترهای wildcard یا لیستی از نام فایل‌ها برای ذخیره‌سازی چندین وابستگی پشتیبانی می‌کند.
    مسیر وابستگی به حافظه پنهان: # اختیاری
                      - نام: محیط راه‌اندازی Node.js
  موارد استفاده: actions/setup-node@v3.9.1
  با:
    # تنظیم always-auth در npmrc.
    always-auth: # اختیاری، پیش‌فرض false است
    # نسخه مشخصات نسخه مورد استفاده. مثال‌ها: 12.x، 10.15.1، >=10.15.0.
    نسخه گره: # اختیاری
    # فایل حاوی نسخه مشخصات نسخه مورد استفاده. مثال‌ها: .nvmrc، .node-version، .tool-versions.
    فایل-نسخه-گره: # اختیاری
    # معماری هدف برای استفاده Node. مثال‌ها: x86، x64. به طور پیش‌فرض از معماری سیستم استفاده خواهد کرد.
    معماری: # اختیاری
    # اگر می‌خواهید اقدام، آخرین نسخه موجود که مشخصات نسخه را برآورده می‌کند، بررسی کند، این گزینه را تنظیم کنید.
    بررسی آخرین: # اختیاری
    # رجیستری اختیاری برای تنظیم برای احراز هویت. رجیستری را در سطح پروژه در فایل‌های .npmrc و .yarnrc تنظیم می‌کند و احراز هویت را برای خواندن از env.NODE_AUTH_TOKEN تنظیم می‌کند.
    آدرس رجیستری: # اختیاری
    # محدوده اختیاری برای احراز هویت در برابر ثبت‌های محدوده‌بندی‌شده. هنگام استفاده از رجیستری بسته‌های گیت‌هاب (https://npm.pkg.github.com/) به مالک مخزن ارجاع داده می‌شود.
    محدوده: # اختیاری
    # برای دریافت توزیع‌های گره از نسخه‌های گره استفاده می‌شود. از آنجایی که یک مقدار پیش‌فرض وجود دارد، معمولاً توسط کاربر ارائه نمی‌شود. هنگام اجرای این اقدام در github.com، مقدار پیش‌فرض کافی است. هنگام اجرا در GHES، اگر با محدودیت سرعت مواجه هستید، می‌توانید یک توکن دسترسی شخصی برای github.com ارسال کنید.
    token: # اختیاری، مقدار پیش‌فرض ${{ github.server_url == 'https://github.com' && github.token || '' }} است
    # برای تعیین یک مدیر بسته برای ذخیره‌سازی در دایرکتوری پیش‌فرض استفاده می‌شود. مقادیر پشتیبانی‌شده: npm، yarn، pnpm.
    حافظه پنهان: # اختیاری
    # برای مشخص کردن مسیر فایل وابستگی استفاده می‌شود: package-lock.json، yarn.lock و غیره. از کاراکترهای wildcard یا لیستی از نام فایل‌ها برای ذخیره‌سازی چندین وابستگی پشتیبانی می‌کند.
    مسیر وابستگی به حافظه پنهان: # اختیاری
                - نام: دانلود یک مصنوع ساخت
  موارد استفاده: actions/download-artifact@v4.3.0
  با:
    # نام مصنوع برای دانلود. اگر مشخص نشده باشد، تمام مصنوعات برای اجرا دانلود می‌شوند.
    نام: # اختیاری
    # شناسه‌ی مصنوعات برای دانلود، جدا شده با کاما. می‌توان از ورودی‌های `artifact-ids` یا `name` استفاده کرد، اما نمی‌توان هر دو را با هم وارد کرد.
    شناسه‌های مصنوعات: # اختیاری
    # مسیر مقصد. از بسط ساده‌ی تیلده پشتیبانی می‌کند. مقدار پیش‌فرض $GITHUB_WORKSPACE است.
    مسیر: # اختیاری
    # یک الگوی glob که با مصنوعاتی که باید دانلود شوند مطابقت دارد. در صورت مشخص شدن نام، نادیده گرفته می‌شود.
    الگو: # اختیاری
    # وقتی چندین مصنوع مطابقت داده می‌شوند، این رفتار دایرکتوری‌های مقصد را تغییر می‌دهد. اگر درست باشد، مصنوعات دانلود شده در همان دایرکتوری مشخص شده توسط مسیر قرار می‌گیرند. اگر نادرست باشد، مصنوعات دانلود شده در دایرکتوری‌های جداگانه با نام مشخص شده در مسیر مشخص شده استخراج می‌شوند.
    ادغام چندگانه: # اختیاری، پیش‌فرض نادرست است
    # توکن گیت‌هاب مورد استفاده برای احراز هویت با API گیت‌هاب. این مورد هنگام دانلود مصنوعات از یک مخزن متفاوت یا از یک اجرای گردش کار متفاوت مورد نیاز است. اگر این مورد مشخص نشده باشد، اکشن تلاش می‌کند مصنوعات را از مخزن فعلی و اجرای گردش کار فعلی دانلود کند.
    github-token: # اختیاری
    # مالک مخزن و نام مخزن که با "/" به هم متصل شده‌اند. اگر github-token مشخص شده باشد، این مخزنی است که مصنوعات از آن دانلود می‌شوند.
    مخزن: # اختیاری، مقدار پیش‌فرض ${{ github.repository }} است
    # شناسه‌ی روند کاری که مصنوعات دانلودی مورد نظر از آن آپلود شده‌اند. اگر github-token مشخص شده باشد، این روندی است که مصنوعات از آن دانلود خواهند شد.
    ‎run-id: # اختیاری، پی
    ش‌فرض ‎${{ github.run_id }}‎ است
    
                - نام: برچسب ساخت داکر، انتشار در ECR
  # می‌توانید دقیقاً به کامیت یا نسخه پین ​​کنید.
  # موارد استفاده: bitovi/github-actions-docker-ecr-publish@bcaf3fb11bafbc6ae884516e92f870ac11a5ae68
  موارد استفاده: bitovi/github-actions-docker-ecr-publish@v0.1.0
  با:
    # بررسی مخزن
    پرداخت: # اختیاری، پیش‌فرض درست است
    # از ورود داخلی با اکشن استفاده کنید
    aws_login: # اختیاری، پیش‌فرض درست است
    # شناسه کلید دسترسی AWS
    شناسه کلید دسترسی aws:
    # کلید دسترسی مخفی AWS
    کلید دسترسی مخفی aws:
    # توکن جلسه AWS
    aws_session_token: # اختیاری
    # منطقه پیش‌فرض AWS
    aws_default_region: # اختیاری، پیش‌فرض us-east-1 است
    # نام مخزن AWS ECR. مثلاً hello-repository
    نام مخزن aws_ecr:
    # برچسب برای لغو منطق پیش‌فرض
    image_tag: # اختیاری، پیش‌فرض
    # از SHA برای تگ استفاده کنید. منطق پیش‌فرض را لغو می‌کند.
    use_sha: # اختیاری
    # نام سازمان داکر.
    org_name: # اختیاری، پیش‌فرض
    # به جای نام شاخه، شاخه پیش‌فرض را با آخرین برچسب برچسب‌گذاری کنید.
    use_latest: # اختیاری، پیش‌فرض درست است
    # اضافه کردن رشته‌ای از مقادیر به انتهای دستور ساخت
    build_args: # اختیاری
    # دایرکتوری کاری که docker build در آن اجرا خواهد شد را مشخص کنید
    working_directory: # اختیاری
          ‎
                      - نام: Terraform برای GorillaStack درخواست دهید
  # می‌توانید دقیقاً به کامیت یا نسخه پین ​​کنید.
  # کاربردها: SWO-GS/github-action-apply-on-merge@71fab58db0a839b1e9b34e87601a5e4347c52c88
  موارد استفاده: SWO-GS/github-action-apply-on-merge@v0.1.0
  با:
    # نوع عمل (در حال حاضر "اعتبارسنجی" و "اعمال" در دسترس هستند)
    اقدام: # پیش‌فرض اعتبارسنجی است
    # نام پشته سطل tfstate
    stack_name: # مقدار پیش‌فرض github-actions-gorillastack-tfstate است
    # منطقه‌ای که پشته سطل tfstate را در آن مستقر کرده‌اید
    aws_default_region: # مقدار پیش‌فرض us-east-1 است
    # شناسه کلید دسترسی AWS برای کاربری که مجوز دسترسی به باکت tfstate را دارد
    aws_access_key_id: # پیش‌فرض برای همه چیز پیش‌فرض است اما اعمال نمی‌شود
    # کلید دسترسی مخفی AWS برای کاربری که امتیاز دسترسی به باکت tfstate را دارد
    aws_secret_access_key: # پیش‌فرض برای همه چیز پیش‌فرض است اما اعمال نمی‌شود
    # کلید API گوریلا استک، که خواندنی-نوشتنی یا فقط خواندنی است و به هویت کاربری شما وابسته است.
    gorillastack_api_key: # پیش‌فرض برای همه چیز پیش‌فرض است اما اعمال نمی‌شود
    # شناسه تیم GorillaStack، زمینه تیم/مستأجر مورد نظر شما را تعیین می‌کند
    gorillastack_team_id: # پیش‌فرض برای همه چیز پیش‌فرض است اما اعمال نمی‌شود
          
          
